### ISSUE TITLE
Activate GitHub Pages on SmartGovLezModel

### ISSUE THREAD

**Issue by elombardi2** [smartgov-liris/SmartGovSimulator#10]
The link to the javadoc in the upcoming [SmartGovLezModel/documentation/README.md](https://github.com/EricBoix/SmartGovLezModel/blob/master/documentation/README.md) file displays the source html code instead of the html page.

To fix this:
1. accept [SmartGovLezModel PR #2](https://github.com/smartgov-liris/SmartGovLezModel/pull/2)
2. activate GitHub Pages on SmartGovLezModel repo
3. in `SmartGovLezModel/documentation/README.md`, replace the link to `/docs/org/liris/smartgov/lez/core/agent/establishment/ST8.html` by a link to `https://smartgov-liris.github.io/SmartGovLezModel/...`

**Comment by elombardi2** [comment]
1. Done
2. Done. But [](https://smartgov-liris.github.io/SmartGovLezModel/) does not display the HTML javadoc.

**Comment by EricBoix** [comment]
Re-activate github pages (as admin) and configure it to use the master/main branch on the `docs` sub-directory (as opposed to the old workflow with a gh-pages branch).

**Comment by vdeslandres** [comment]
Done, it works now, thanks
