### ISSUE TITLE
PR from AlbanFl/SmartGovSimulator to smartgov-liris/SmartGovSimulator

### ISSUE THREAD

**Issue by EricBoix** [smartgov-liris/SmartGovSimulator#4]
Pull back Alban Flandin's derived work [from his AlbanFl/SmartGovSimulator fork](https://github.com/AlbanFl/SmartGovSimulator) to the [reference smartgov-liris/SmartGovSimulator](https://github.com/smartgov-liris/SmartGovSimulator).

This corresponds 
 1. first accepting PR #2 first (to activate the CI).
 2. then accepting [PR #1](https://github.com/smartgov-liris/SmartGovSimulator/pull/1) 

Note: this PR looks quite straightforward since they are [few differences](https://github.com/smartgov-liris/SmartGovSimulator/compare/master...AlbanFl:master)

**Comment by elombardi2** [comment]
Prior to pulling from AlbanFl/SmartGovSimulator, remember to pull from [EricBoix/SmartGovSimulator](https://github.com/EricBoix/SmartGovSimulator) to get the tests and the CI.

**Comment by vdeslandres** [comment]
Done with success
