### ISSUE TITLE
Restructure the Instance models repositories

### ISSUE THREAD

**Issue by EricBoix** [smartgov-liris/SmartGovSimulator#5]
They are two instance models repositories baring the same name that are completely different models.
In order to avoid confusing them 
  1. rename smartgov-liris/SmartGovLezModel to smartgov-liris/LezModelUFD (Urban Freight Delivery)
  2. move AlbanFl/SmartGovLezModel to become the now freed smartgov-liris/SmartGovLezModel
 
In action this boils down to
1. Git clone --bare AlbanFl/SmartGovLezModel (i.e. save it locally to avoid loosing content) 
2. Through github web interface (go to the Settings tab of the repository, just after the Insights tab on the landing page), rename smartgov-liris/SmartGovLezModel to smartgov-liris/SmartGovLezModelUFD,
3. Create a new smartgov-liris/SmartGovLezModel. Not that this will break the github created redirections from smartgov-liris/SmartGovLezModel to smartgov-liris/SmartGovLezModelUFD that were automatically set in place by github when doing the repository rename: BUT **this is what we need** to re-use the smartgov-liris/SmartGovLezModel repository name
4. `cd SmartGovLezModel/ && git push --mirror https://github.com/smartgov-liris/SmartGovLezModel`

**Comment by elombardi2** [comment]
Prior to rename smartgov-liris/SmartGovLezModel, pull from [elombardi2/SmartGovLezModel](https://github.com/elombardi2/SmartGovLezModel) to get the tests and the CI.
