### ISSUE TITLE
Create docker repository AND provide content

### ISSUE THREAD

**Issue by EricBoix** [smartgov-liris/SmartGovSimulator#6]
Note: work was already done [here](https://gitlab.liris.cnrs.fr/edp/smartgov/tree/master/elo_tmp/docker)

Create a new SmartGov-docker repository

Each subidrectory will hold a specific instance model container:
 - SmartGovLezModel
 - SmartGovLezModelUFD
 - SmartGovExampleModel
 - lezviewer (to be checked: export site with e.g. python -m)

**Comment by vdeslandres** [comment]
Just done!

**Comment by EricBoix** [comment]
@vdeslandres Thanks for repository creation ! Still I'm reopening this issue because we know
need to provide some content to the repository (which is described in this issue).

**Comment by EricBoix** [comment]
Done.
