### ISSUE TITLE
Transfer/copy AlbanFl/SmartGovNN repo to the smartgov-liris organization

### ISSUE THREAD

**Issue by elombardi2** [smartgov-liris/SmartGovSimulator#9]
[SmartGovLezModel/documentation/README.md](https://github.com/EricBoix/SmartGovLezModel/blob/master/documentation/README.md) points to [AlbanFl/SmartGovNN](https://github.com/AlbanFl/SmartGovNN).

It looks like the [AlbanFl/SmartGovNN](https://github.com/AlbanFl/SmartGovNN) repo (where NN stands for Neural Network) is used by [SmartGovSimulator](https://github.com/smartgov-liris/SmartGovSimulator) or [SmartGovLezModel](https://github.com/smartgov-liris/SmartGovLezModel).

Is this the case ? (checked it out with VDE)

If this where to be the case then transfer/copy this [AlbanFl/SmartGovNN](https://github.com/AlbanFl/SmartGovNN) into [smartgov-liris organization](https://github.com/smartgov-liris).

**Comment by vdeslandres** [comment]
Yes, the [AlbanFl/SmartGovNN](https://github.com/AlbanFl/SmartGovNN) repo is a python code for genetic algorithms used by [SmartGovLezModel] (https://github.com/smartgov-liris/SmartGovLezModel) to determine the optimal policy given one environment and a file containing past results of simulations.

**Comment by vdeslandres** [comment]
Do I have to transfer the [AlbanFl/SmartGovNN](https://github.com/AlbanFl/SmartGovNN) as we proceeded with git clone --bare for the LezModel repo ?

**Comment by vdeslandres** [comment]
Done
